import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import { FaDownload, FaFacebook, FaInstagram, FaTwitter, FaLinkedin } from 'react-icons/fa';
import Link from "next/link";

export default function Resume() {
    const [darkMode, setDarkMode] = useState(true);

    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Istiaq Ahmed</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
                <section className="min-h-screen">
                    <nav className="py-10 mb-12 flex justify-between dark:text-white">
                        <Link href="/">
                            <h1 className="font-burtons text-2xl">Istiaq Ahmed</h1>
                        </Link>
                        <ul className="flex items-center">
                            <li style={{ position: 'fixed', bottom: '20px', right: '40px' }}>
                                <BsFillMoonStarsFill
                                    onClick={() => setDarkMode(!darkMode)}
                                    className=" cursor-pointer text-2xl"
                                />
                            </li>
                            <li>
                                <Link href="/Resume">
                                    <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8">
                                        Resume
                                    </a>
                                </Link>
                            </li>
                            <li>
                                <Link href="/Portfolio">
                                    <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8">
                                        Portfolio
                                    </a>
                                </Link>
                            </li>
                            <li style={{ position: 'fixed', bottom: '20px', left: '40px' }}>
                                <a href="/path/to/download" download>
                                    <FaDownload className="text-2xl cursor-pointer" />
                                </a>
                            </li>
                            <ul className="fixed bottom-0 left-1/2 transform -translate-x-1/2 flex justify-center items-center py-4 z-10">
                                <li className="mx-4">
                                    <a href="https://twitter.com/yourtwitterhandle" target="_blank" rel="noopener noreferrer">
                                        <FaTwitter className="text-4xl" />
                                    </a>
                                </li>
                                <li className="mx-4">
                                    <a href="https://www.linkedin.com/in/yourlinkedinprofile" target="_blank" rel="noopener noreferrer">
                                        <FaLinkedin className="text-4xl" />
                                    </a>
                                </li>
                                <li className="mx-4">
                                    <a href="https://www.facebook.com/yourfacebookprofile" target="_blank" rel="noopener noreferrer">
                                        <FaFacebook className="text-4xl" />
                                    </a>
                                </li>
                                <li className="mx-4">
                                    <a href="https://www.instagram.com/yourinstagramprofile" target="_blank" rel="noopener noreferrer">
                                        <FaInstagram className="text-4xl" />
                                    </a>
                                </li>
                            </ul>

                        </ul>
                    </nav>
                    <section className="py-10">
                        <h2 className="text-3xl -mt-12 font-medium py-4 dark:text-white">Skills</h2>
                    </section>
                    <section className="py-10 -mt-16 grid gap-6 lg:grid-cols-3">
                        <div className="p-4 bg-white rounded-lg shadow-md dark:bg-gray-800">
                            <h3 className="text-2xl font-medium py-2 dark:text-white">Programming Languages</h3>
                            <ul className="list-disc list-inside py-2 dark:text-gray-200">
                                <li>JavaScript</li>
                                <li>Python</li>
                                <li>PHP</li>
                            </ul>
                        </div>
                        <div className="p-4 bg-white rounded-lg shadow-md dark:bg-gray-800">
                            <h3 className="text-2xl font-medium py-2 dark:text-white">Web Development</h3>
                            <ul className="list-disc list-inside py-2 dark:text-gray-200">
                                <li>HTML</li>
                                <li>CSS</li>
                                <li>React</li>
                                <li>Node.js</li>
                            </ul>
                        </div>
                        <div className="p-4 bg-white rounded-lg shadow-md dark:bg-gray-800">
                            <h3 className="text-2xl font-medium py-2 dark:text-white">Design Tools</h3>
                            <ul className="list-disc list-inside py-2 dark:text-gray-200">
                                <li>Figma</li>
                                <li>Photoshop</li>
                                <li>Illustrator</li>
                            </ul>
                        </div>
                        <div className="p-4 bg-white rounded-lg shadow-md dark:bg-gray-800">
                            <h3 className="text-2xl font-medium py-2 dark:text-white">Design Tools</h3>
                            <ul className="list-disc list-inside py-2 dark:text-gray-200">
                                <li>Figma</li>
                                <li>Photoshop</li>
                                <li>Illustrator</li>
                            </ul>
                        </div>
                    </section>
                    <section className="py-10">
                        <h2 className="text-3xl -mt-12 font-medium py-4 dark:text-white">Experience</h2>
                        <div className="py-4 dark:text-gray-200">
                            <h3 className="text-xl font-medium text-teal-500">
                                Web Developer
                            </h3>
                            <p className="text-md py-1 text-teal-500">
                                ABC Company
                            </p>
                            <p className="text-md py-1 text-gray-400">
                                Oct 2021 - Present
                            </p>
                            <p className="text-md py-2">
                                - Developed and maintained web applications using React, Node.js, and MongoDB<br />
                                - Implemented responsive design and accessibility best practices<br />
                                - Collaborated with cross-functional teams to deliver high-quality software products
                            </p>
                        </div>
                        <div className="py-4 dark:text-gray-200">
                            <h3 className="text-xl font-medium text-yellow-500">
                                Software Engineer
                            </h3>
                            <p className="text-md py-1 text-yellow-500">
                                XYZ Corporation
                            </p>
                            <p className="text-md py-1 text-gray-400">
                                Jan 2019 - Sep 2021
                            </p>
                            <p className="text-md py-2">
                                - Designed and developed microservices using Java and Spring Boot<br />
                                - Created and maintained SQL databases to support applications<br />
                                - Worked closely with project managers to deliver solutions on time and within budget
                            </p>
                        </div>
                        <div className="py-4 dark:text-gray-200">
                            <h3 className="text-xl font-medium text-red-500">
                                UX Designer
                            </h3>
                            <p className="text-md py-1 text-red-500">
                                PQR Agency
                            </p>
                            <p className="text-md py-1 text-gray-400">
                                Jun 2017 - Dec 2018
                            </p>
                            <p className="text-md py-2">
                                - Conducted user research and created wireframes and prototypes<br />
                                - Designed interfaces for web and mobile applications using Sketch and Adobe Creative Suite<br />
                                - Collaborated with developers to ensure designs were implemented accurately and efficiently
                            </p>
                        </div>
                    </section>
                    <section className="py-10">
                        <h2 className="text-3xl -mt-12 font-medium py-4 dark:text-white">Education</h2>
                        <div className="py-4 dark:text-gray-200">
                            <h3 className="text-xl font-medium text-teal-500">
                                Bachelor of Science, Computer Science
                            </h3>
                            <p className="text-md py-1 text-teal-500">
                                University of ABC
                            </p>
                            <p className="text-md py-1 text-gray-400">
                                Aug 2015 - May 2019
                            </p>
                            <p className="text-md py-2">
                                Relevant coursework: Algorithms, Data Structures, Web Development, Human-Computer Interaction
                            </p>
                        </div>
                        <div className="py-4 dark:text-gray-200">
                            <h3 className="text-xl font-medium text-yellow-500">
                                Master of Science, Information Systems
                            </h3>
                            <p className="text-md py-1 text-yellow-500">
                                XYZ University
                            </p>
                            <p className="text-md py-1 text-gray-400">
                                Aug 2019 - May 2021
                            </p>
                            <p className="text-md py-2">
                                Relevant coursework: Database Management, Information Security, Software Engineering, Project Management
                            </p>
                        </div>
                        <div className="py-4 dark:text-gray-200">
                            <h3 className="text-xl font-medium text-red-500">
                                Bachelor of Arts, Graphic Design
                            </h3>
                            <p className="text-md py-1 text-red-500">
                                MNO College
                            </p>
                            <p className="text-md py-1 text-gray-400">
                                Aug 2013 - May 2017
                            </p>
                            <p className="text-md py-2">
                                Relevant coursework: Typography, Branding, User Experience Design, Illustration
                            </p>
                        </div>
                    </section>
                </section>
            </main>
        </div>
    );
}
